import os
import sys

import networkx as nx
import pandas as pd
import streamlit as st
import streamlit.components.v1 as components
from pyvis.network import Network

# Add the project root to the Python path for local execution.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.analyzer import PacketAnalyzer
from app.database import DatabaseManager
from app.detection_engine import DetectionEngine
from app.rules_engine import RulesEngine
from app.sniffer import PacketSniffer


st.set_page_config(
    page_title="NetSentinel | Network Metadata Prototype",
    page_icon="NS",
    layout="wide",
)

st.markdown(
    """
    <style>
    .main {
        background-color: #0d1117;
        color: #c9d1d9;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    .block-container {
        padding-top: 3rem;
        padding-bottom: 3rem;
    }
    h1, h2, h3 {
        color: #58a6ff !important;
        letter-spacing: 0.5px;
    }
    .stButton>button {
        background-color: #238636;
        color: white;
        border: none;
        width: 100%;
        border-radius: 8px;
        padding: 0.6rem 1rem;
    }
    .stButton>button:hover {
        background-color: #2ea043;
        color: white;
    }
    .hero {
        border: 1px solid #30363d;
        background: linear-gradient(135deg, #111827 0%, #0d1117 65%);
        border-radius: 18px;
        padding: 2rem;
        margin-bottom: 1.5rem;
    }
    .hero-title {
        font-size: 2.4rem;
        font-weight: 800;
        color: #58a6ff;
        margin-bottom: 0.3rem;
    }
    .hero-subtitle {
        color: #8b949e;
        font-size: 1rem;
        max-width: 760px;
    }
    .metric-card {
        border: 1px solid #30363d;
        background: #161b22;
        border-radius: 14px;
        padding: 1.2rem;
        min-height: 118px;
    }
    .metric-label {
        color: #8b949e;
        font-size: 0.85rem;
        margin-bottom: 0.5rem;
    }
    .metric-value {
        color: #f0f6fc;
        font-size: 2rem;
        font-weight: 800;
    }
    .metric-help {
        color: #6e7681;
        font-size: 0.8rem;
        margin-top: 0.4rem;
    }
    .empty-state {
        border: 1px dashed #30363d;
        background: rgba(22, 27, 34, 0.65);
        border-radius: 16px;
        padding: 1.5rem;
        margin-top: 1rem;
    }
    .empty-state h3 {
        margin-top: 0;
    }
    .step-list li {
        margin-bottom: 0.45rem;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


@st.cache_resource
def get_db():
    return DatabaseManager()


@st.cache_resource
def get_components(_db):
    rules_engine = RulesEngine()

    try:
        analyzer = PacketAnalyzer(_db)
    except TypeError:
        analyzer = PacketAnalyzer()

    detection_engine = DetectionEngine(rules_engine, _db)

    try:
        sniffer = PacketSniffer(_db, analyzer, detection_engine)
    except TypeError:
        sniffer = PacketSniffer(_db, detection_engine)

    return {
        "rules_engine": rules_engine,
        "analyzer": analyzer,
        "detection_engine": detection_engine,
        "sniffer": sniffer,
    }


def metric_card(label, value, help_text=""):
    st.markdown(
        f"""
        <div class="metric-card">
            <div class="metric-label">{label}</div>
            <div class="metric-value">{value}</div>
            <div class="metric-help">{help_text}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def safe_get_connections(analyzer):
    try:
        return analyzer.get_connections()
    except Exception:
        return []


def show_branding():
    logo_path = "assets/logo.svg"
    if os.path.exists(logo_path):
        st.sidebar.image(logo_path, width=140)
    st.sidebar.title("NetSentinel")
    st.sidebar.caption("Educational network metadata monitoring prototype")


db = get_db()
app_components = get_components(db)


def overview_page():
    st.markdown(
        """
        <div class="hero">
            <div class="hero-title">Platform Overview</div>
            <div class="hero-subtitle">
                NetSentinel is running locally. This page shows stored packet metadata,
                generated alerts, active connection relationships, and the current lab status.
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    alerts = db.get_alerts(limit=1000)
    packets = db.get_packets(limit=1000)
    connections = safe_get_connections(app_components["analyzer"])
    critical_alerts = [alert for alert in alerts if alert.severity == "Critical"]

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        metric_card("Stored Packets", len(packets), "Saved in the local SQLite database")
    with col2:
        metric_card("Alerts", len(alerts), "Generated by detection rules")
    with col3:
        metric_card("Critical Alerts", len(critical_alerts), "Highest severity events")
    with col4:
        metric_card("Connections", len(connections), "Tracked during the current run")

    if not packets and not alerts and not connections:
        st.markdown(
            """
            <div class="empty-state">
                <h3>No traffic data yet</h3>
                <p>The dashboard is working, but the local database does not contain captured packet metadata yet.</p>
                <ul class="step-list">
                    <li>Use <strong>Start Local Collection</strong> only in a lab or authorized network.</li>
                    <li>Run the app with the required system permissions if live collection is needed.</li>
                    <li>PCAP ingestion is listed as roadmap work, so this screen currently focuses on stored metadata and alerts.</li>
                </ul>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.markdown("---")
    st.subheader("Network Relationship View")

    if connections:
        graph = nx.Graph()
        for connection in connections[:50]:
            source = connection.get("source_ip")
            destination = connection.get("dest_ip")
            if source and destination:
                graph.add_edge(source, destination)

        if graph.nodes:
            net = Network(height="420px", width="100%", bgcolor="#0d1117", font_color="white")
            net.from_nx(graph)
            graph_path = "network_graph.html"
            net.save_graph(graph_path)
            with open(graph_path, "r", encoding="utf-8") as graph_file:
                components.html(graph_file.read(), height=460)
        else:
            st.info("No connection relationships are available yet.")
    else:
        st.info("No connection data is available yet.")


def analysis_page():
    st.title("Analysis Workspace")
    st.subheader("Traffic Statistics")

    analyzer = app_components["analyzer"]

    if hasattr(analyzer, "get_all_traffic_stats"):
        stats = analyzer.get_all_traffic_stats()
    elif hasattr(analyzer, "get_traffic_stats"):
        stats = analyzer.get_traffic_stats()
    else:
        stats = {}

    if stats:
        rows = []
        for ip_address, values in stats.items():
            rows.append(
                {
                    "Host": ip_address,
                    "Packets": values.get("total_packets", 0),
                    "Bytes": values.get("total_bytes", 0),
                }
            )
        st.dataframe(pd.DataFrame(rows), use_container_width=True)
    else:
        st.info("No traffic statistics are available yet.")

    st.subheader("PCAP Analysis")
    st.info(
        "The PCAP workflow is part of the project roadmap. The current dashboard focuses on stored metadata and alert review."
    )


def alerts_page():
    st.title("Security Alerts")

    alerts = db.get_alerts(limit=100)

    if not alerts:
        st.info("No alerts are stored yet.")
        return

    alert_rows = [
        {
            "Time": alert.timestamp,
            "Type": alert.alert_type,
            "Severity": alert.severity,
            "Source": alert.source_ip,
            "Destination": alert.dest_ip,
            "Description": alert.description,
        }
        for alert in alerts
    ]

    st.dataframe(pd.DataFrame(alert_rows), use_container_width=True)


def main():
    show_branding()

    page = st.sidebar.radio("Navigation", ["Overview", "Analysis", "Alerts"])

    if st.sidebar.button("Start Local Collection"):
        try:
            app_components["sniffer"].start_sniffing()
            st.sidebar.success("Collection requested. System permissions may be required.")
        except Exception as error:
            st.sidebar.error(f"Unable to start collection: {error}")

    if page == "Overview":
        overview_page()
    elif page == "Analysis":
        analysis_page()
    elif page == "Alerts":
        alerts_page()


if __name__ == "__main__":
    main()
